TOKEN_SPECS = [
    ('NUMBER', r'\d+(\.\d+)?'),
    ('TEXT', r'"[^"]*"'),
    ('ASSIGN', r':='),
    ('PLUS', r'\+'),
    ('MINUS', r'-'),
    ('MULT', r'\*'),
    ('DIV', r'/'),
    ('LT', r'<'),
    ('GT', r'>'),
    ('EQ', r'=='),
    ('LPAREN', r'\('),
    ('RPAREN', r'\)'),
    ('LBRACE', r'\{'),
    ('RBRACE', r'\}'),
    ('DOT', r'\.'),
    ('COMMA', r','),
    ('SEMIC', r';'),
    ('SKIP', r'[ \t\n]+'),
    ('ID', r'[A-Za-z][A-Za-z0-9]*'),
]

KEYWORDS = {
    'programu': 'PROGRAM',
    'mwisho': 'END',
    'nambari': 'INT',
    'kuelea': 'FLOAT',
    'kamba': 'STRING',
    'kweli': 'BOOLEAN_TRUE',
    'uongo': 'BOOLEAN_FALSE',
    'ikiwa': 'IF',
    'sivyo': 'ELIF',
    'mwingine': 'ELSE',
    'wakati': 'WHILE',
    'kwa': 'FOR',
    'pembejeo': 'INPUT',
    'chapa': 'PRINT',
}